[workspace]
resolver = "2"
members = [
    "duke",
    "crates/duke-classfile",
    "crates/duke-bytecode",
    "crates/duke-loader",
    "crates/duke-runtime",
    "crates/duke-gc",
    "crates/duke-interpreter",
    "crates/duke-telemetry",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["Mark"]

[workspace.dependencies]
thiserror = "2"
proptest = "1"
bitflags = "2"
flate2 = "1"
regex = "1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

[profile.profiling]
inherits = "release"
debug = 1
