coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
    patch:
      default:
        target: 10%
        threshold: 0.1%

ignore:
  - "crates/duke-interpreter/src/native/mod.rs"
