use duke_bytecode::instruction::{ArrayType, Instruction};
use duke_classfile::types::CpIndex;

#[test]
fn should_test_instruction_variants() {
    let variants = vec![
        (Instruction::Nop, "nop"),
        (Instruction::AconstNull, "aconst_null"),
        (Instruction::IconstM1, "iconst_m1"),
        (Instruction::Iconst0, "iconst_0"),
        (Instruction::Iconst1, "iconst_1"),
        (Instruction::Iconst2, "iconst_2"),
        (Instruction::Iconst3, "iconst_3"),
        (Instruction::Iconst4, "iconst_4"),
        (Instruction::Iconst5, "iconst_5"),
        (Instruction::Lconst0, "lconst_0"),
        (Instruction::Lconst1, "lconst_1"),
        (Instruction::Fconst0, "fconst_0"),
        (Instruction::Fconst1, "fconst_1"),
        (Instruction::Fconst2, "fconst_2"),
        (Instruction::Dconst0, "dconst_0"),
        (Instruction::Dconst1, "dconst_1"),
        (Instruction::Bipush(42), "bipush"),
        (Instruction::Sipush(4242), "sipush"),
        (Instruction::Ldc(1), "ldc"),
        (Instruction::LdcW(CpIndex(1)), "ldc_w"),
        (Instruction::Ldc2W(CpIndex(1)), "ldc2_w"),
        (Instruction::Iload(1), "iload"),
        (Instruction::Lload(1), "lload"),
        (Instruction::Fload(1), "fload"),
        (Instruction::Dload(1), "dload"),
        (Instruction::Aload(1), "aload"),
        (Instruction::Iload0, "iload_0"),
        (Instruction::Iload1, "iload_1"),
        (Instruction::Iload2, "iload_2"),
        (Instruction::Iload3, "iload_3"),
        (Instruction::Lload0, "lload_0"),
        (Instruction::Lload1, "lload_1"),
        (Instruction::Lload2, "lload_2"),
        (Instruction::Lload3, "lload_3"),
        (Instruction::Fload0, "fload_0"),
        (Instruction::Fload1, "fload_1"),
        (Instruction::Fload2, "fload_2"),
        (Instruction::Fload3, "fload_3"),
        (Instruction::Dload0, "dload_0"),
        (Instruction::Dload1, "dload_1"),
        (Instruction::Dload2, "dload_2"),
        (Instruction::Dload3, "dload_3"),
        (Instruction::Aload0, "aload_0"),
        (Instruction::Aload1, "aload_1"),
        (Instruction::Aload2, "aload_2"),
        (Instruction::Aload3, "aload_3"),
        (Instruction::Iaload, "iaload"),
        (Instruction::Laload, "laload"),
        (Instruction::Faload, "faload"),
        (Instruction::Daload, "daload"),
        (Instruction::Aaload, "aaload"),
        (Instruction::Baload, "baload"),
        (Instruction::Caload, "caload"),
        (Instruction::Saload, "saload"),
        (Instruction::Istore(1), "istore"),
        (Instruction::Lstore(1), "lstore"),
        (Instruction::Fstore(1), "fstore"),
        (Instruction::Dstore(1), "dstore"),
        (Instruction::Astore(1), "astore"),
        (Instruction::Istore0, "istore_0"),
        (Instruction::Istore1, "istore_1"),
        (Instruction::Istore2, "istore_2"),
        (Instruction::Istore3, "istore_3"),
        (Instruction::Lstore0, "lstore_0"),
        (Instruction::Lstore1, "lstore_1"),
        (Instruction::Lstore2, "lstore_2"),
        (Instruction::Lstore3, "lstore_3"),
        (Instruction::Fstore0, "fstore_0"),
        (Instruction::Fstore1, "fstore_1"),
        (Instruction::Fstore2, "fstore_2"),
        (Instruction::Fstore3, "fstore_3"),
        (Instruction::Dstore0, "dstore_0"),
        (Instruction::Dstore1, "dstore_1"),
        (Instruction::Dstore2, "dstore_2"),
        (Instruction::Dstore3, "dstore_3"),
        (Instruction::Astore0, "astore_0"),
        (Instruction::Astore1, "astore_1"),
        (Instruction::Astore2, "astore_2"),
        (Instruction::Astore3, "astore_3"),
        (Instruction::Iastore, "iastore"),
        (Instruction::Lastore, "lastore"),
        (Instruction::Fastore, "fastore"),
        (Instruction::Dastore, "dastore"),
        (Instruction::Aastore, "aastore"),
        (Instruction::Bastore, "bastore"),
        (Instruction::Castore, "castore"),
        (Instruction::Sastore, "sastore"),
        (Instruction::Pop, "pop"),
        (Instruction::Pop2, "pop2"),
        (Instruction::Dup, "dup"),
        (Instruction::DupX1, "dup_x1"),
        (Instruction::DupX2, "dup_x2"),
        (Instruction::Dup2, "dup2"),
        (Instruction::Dup2X1, "dup2_x1"),
        (Instruction::Dup2X2, "dup2_x2"),
        (Instruction::Swap, "swap"),
        (Instruction::Iadd, "iadd"),
        (Instruction::Ladd, "ladd"),
        (Instruction::Fadd, "fadd"),
        (Instruction::Dadd, "dadd"),
        (Instruction::Isub, "isub"),
        (Instruction::Lsub, "lsub"),
        (Instruction::Fsub, "fsub"),
        (Instruction::Dsub, "dsub"),
        (Instruction::Imul, "imul"),
        (Instruction::Lmul, "lmul"),
        (Instruction::Fmul, "fmul"),
        (Instruction::Dmul, "dmul"),
        (Instruction::Idiv, "idiv"),
        (Instruction::Ldiv, "ldiv"),
        (Instruction::Fdiv, "fdiv"),
        (Instruction::Ddiv, "ddiv"),
        (Instruction::Irem, "irem"),
        (Instruction::Lrem, "lrem"),
        (Instruction::Frem, "frem"),
        (Instruction::Drem, "drem"),
        (Instruction::Ineg, "ineg"),
        (Instruction::Lneg, "lneg"),
        (Instruction::Fneg, "fneg"),
        (Instruction::Dneg, "dneg"),
        (Instruction::Ishl, "ishl"),
        (Instruction::Lshl, "lshl"),
        (Instruction::Ishr, "ishr"),
        (Instruction::Lshr, "lshr"),
        (Instruction::Iushr, "iushr"),
        (Instruction::Lushr, "lushr"),
        (Instruction::Iand, "iand"),
        (Instruction::Land, "land"),
        (Instruction::Ior, "ior"),
        (Instruction::Lor, "lor"),
        (Instruction::Ixor, "ixor"),
        (Instruction::Lxor, "lxor"),
        (Instruction::Iinc { index: 1, value: 1 }, "iinc"),
        (Instruction::I2l, "i2l"),
        (Instruction::I2f, "i2f"),
        (Instruction::I2d, "i2d"),
        (Instruction::L2i, "l2i"),
        (Instruction::L2f, "l2f"),
        (Instruction::L2d, "l2d"),
        (Instruction::F2i, "f2i"),
        (Instruction::F2l, "f2l"),
        (Instruction::F2d, "f2d"),
        (Instruction::D2i, "d2i"),
        (Instruction::D2l, "d2l"),
        (Instruction::D2f, "d2f"),
        (Instruction::I2b, "i2b"),
        (Instruction::I2c, "i2c"),
        (Instruction::I2s, "i2s"),
        (Instruction::Lcmp, "lcmp"),
        (Instruction::Fcmpl, "fcmpl"),
        (Instruction::Fcmpg, "fcmpg"),
        (Instruction::Dcmpl, "dcmpl"),
        (Instruction::Dcmpg, "dcmpg"),
        (Instruction::Ifeq(1), "ifeq"),
        (Instruction::Ifne(1), "ifne"),
        (Instruction::Iflt(1), "iflt"),
        (Instruction::Ifge(1), "ifge"),
        (Instruction::Ifgt(1), "ifgt"),
        (Instruction::Ifle(1), "ifle"),
        (Instruction::IfIcmpeq(1), "if_icmpeq"),
        (Instruction::IfIcmpne(1), "if_icmpne"),
        (Instruction::IfIcmplt(1), "if_icmplt"),
        (Instruction::IfIcmpge(1), "if_icmpge"),
        (Instruction::IfIcmpgt(1), "if_icmpgt"),
        (Instruction::IfIcmple(1), "if_icmple"),
        (Instruction::IfAcmpeq(1), "if_acmpeq"),
        (Instruction::IfAcmpne(1), "if_acmpne"),
        (Instruction::Goto(1), "goto"),
        (Instruction::Jsr(1), "jsr"),
        (Instruction::Ret(1), "ret"),
        (Instruction::Tableswitch {
            default: 1,
            low: 1,
            high: 2,
            offsets: vec![1, 2],
        }, "tableswitch"),
        (Instruction::Lookupswitch {
            default: 1,
            pairs: vec![(1, 1), (2, 2)],
        }, "lookupswitch"),
        (Instruction::Ireturn, "ireturn"),
        (Instruction::Lreturn, "lreturn"),
        (Instruction::Freturn, "freturn"),
        (Instruction::Dreturn, "dreturn"),
        (Instruction::Areturn, "areturn"),
        (Instruction::Return, "return"),
        (Instruction::Getstatic(CpIndex(1)), "getstatic"),
        (Instruction::Putstatic(CpIndex(1)), "putstatic"),
        (Instruction::Getfield(CpIndex(1)), "getfield"),
        (Instruction::Putfield(CpIndex(1)), "putfield"),
        (Instruction::Invokevirtual(CpIndex(1)), "invokevirtual"),
        (Instruction::Invokespecial(CpIndex(1)), "invokespecial"),
        (Instruction::Invokestatic(CpIndex(1)), "invokestatic"),
        (Instruction::Invokeinterface {
            index: CpIndex(1),
            count: 1,
        }, "invokeinterface"),
        (Instruction::Invokedynamic(CpIndex(1)), "invokedynamic"),
        (Instruction::New(CpIndex(1)), "new"),
        (Instruction::Newarray(ArrayType::Int), "newarray"),
        (Instruction::Anewarray(CpIndex(1)), "anewarray"),
        (Instruction::Arraylength, "arraylength"),
        (Instruction::Athrow, "athrow"),
        (Instruction::Checkcast(CpIndex(1)), "checkcast"),
        (Instruction::Instanceof(CpIndex(1)), "instanceof"),
        (Instruction::Monitorenter, "monitorenter"),
        (Instruction::Monitorexit, "monitorexit"),
        (Instruction::Multianewarray {
            index: CpIndex(1),
            dimensions: 1,
        }, "multianewarray"),
        (Instruction::Ifnull(1), "ifnull"),
        (Instruction::Ifnonnull(1), "ifnonnull"),
        (Instruction::GotoW(1), "goto_w"),
        (Instruction::JsrW(1), "jsr_w"),
        (Instruction::IloadW(1), "wide iload"),
        (Instruction::LloadW(1), "wide lload"),
        (Instruction::FloadW(1), "wide fload"),
        (Instruction::DloadW(1), "wide dload"),
        (Instruction::AloadW(1), "wide aload"),
        (Instruction::IstoreW(1), "wide istore"),
        (Instruction::LstoreW(1), "wide lstore"),
        (Instruction::FstoreW(1), "wide fstore"),
        (Instruction::DstoreW(1), "wide dstore"),
        (Instruction::AstoreW(1), "wide astore"),
        (Instruction::RetW(1), "wide ret"),
        (Instruction::IincW { index: 1, value: 1 }, "wide iinc"),
    ];

    for (variant, expected) in variants {
        assert_eq!(variant.mnemonic(), expected);
    }
}

#[test]
fn should_test_array_type_from_u8() {
    assert_eq!(ArrayType::from_u8(4), Some(ArrayType::Boolean));
    assert_eq!(ArrayType::from_u8(5), Some(ArrayType::Char));
    assert_eq!(ArrayType::from_u8(6), Some(ArrayType::Float));
    assert_eq!(ArrayType::from_u8(7), Some(ArrayType::Double));
    assert_eq!(ArrayType::from_u8(8), Some(ArrayType::Byte));
    assert_eq!(ArrayType::from_u8(9), Some(ArrayType::Short));
    assert_eq!(ArrayType::from_u8(10), Some(ArrayType::Int));
    assert_eq!(ArrayType::from_u8(11), Some(ArrayType::Long));
    assert_eq!(ArrayType::from_u8(12), None);
}
