[package]
name = "duke-bytecode-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.duke-bytecode]
path = ".."

[[bin]]
name = "decode_bytecode"
path = "fuzz_targets/decode_bytecode.rs"
test = false
doc = false
bench = false

[workspace]
