//! `duke-classfile::access_flags` — Class, field, and method access flags

use bitflags::bitflags;

bitflags! {
    /// Access flags for class declarations (§4.1, Table 4.1-B).
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_classfile::access_flags::ClassAccessFlags;
    ///
    /// let flags = ClassAccessFlags::PUBLIC | ClassAccessFlags::FINAL;
    /// assert!(flags.contains(ClassAccessFlags::PUBLIC));
    /// assert!(!flags.contains(ClassAccessFlags::ABSTRACT));
    ///
    /// // trigger derive Debug, Clone, Copy, PartialEq, Eq
    /// let cloned = flags.clone();
    /// assert_eq!(flags, cloned);
    /// format!("{:?}", flags);
    /// ```
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct ClassAccessFlags: u16 {
        /// Declared public; may be accessed from outside its package.
        const PUBLIC     = 0x0001;
        /// Declared final; no subclasses allowed.
        const FINAL      = 0x0010;
        /// Treat superclass methods specially when invoked by the invokespecial instruction.
        const SUPER      = 0x0020;
        /// Is an interface, not a class.
        const INTERFACE  = 0x0200;
        /// Declared abstract; must not be instantiated.
        const ABSTRACT   = 0x0400;
        /// Declared synthetic; not present in the source code.
        const SYNTHETIC  = 0x1000;
        /// Declared as an annotation type.
        const ANNOTATION = 0x2000;
        /// Declared as an enum type.
        const ENUM       = 0x4000;
        /// Is a module, not a class or interface.
        const MODULE     = 0x8000;
    }
}

bitflags! {
    /// Access flags for field declarations (§4.5, Table 4.5-A).
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_classfile::access_flags::FieldAccessFlags;
    ///
    /// let flags = FieldAccessFlags::PRIVATE | FieldAccessFlags::STATIC;
    /// assert!(flags.contains(FieldAccessFlags::STATIC));
    /// assert!(!flags.contains(FieldAccessFlags::PUBLIC));
    ///
    /// // trigger derive Debug, Clone, Copy, PartialEq, Eq
    /// let cloned = flags.clone();
    /// assert_eq!(flags, cloned);
    /// format!("{:?}", flags);
    /// ```
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct FieldAccessFlags: u16 {
        /// Declared public; may be accessed from outside its package.
        const PUBLIC    = 0x0001;
        /// Declared private; usable only within the defining class.
        const PRIVATE   = 0x0002;
        /// Declared protected; may be accessed within subclasses.
        const PROTECTED = 0x0004;
        /// Declared static.
        const STATIC    = 0x0008;
        /// Declared final; no further assignment after initialization.
        const FINAL     = 0x0010;
        /// Declared volatile; cannot be cached.
        const VOLATILE  = 0x0040;
        /// Declared transient; not written or read by a persistent object manager.
        const TRANSIENT = 0x0080;
        /// Declared synthetic; not present in the source code.
        const SYNTHETIC = 0x1000;
        /// Declared as an element of an enum.
        const ENUM      = 0x4000;
    }
}

bitflags! {
    /// Access flags for method declarations (§4.6, Table 4.6-A).
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_classfile::access_flags::MethodAccessFlags;
    ///
    /// let flags = MethodAccessFlags::PUBLIC | MethodAccessFlags::STATIC;
    /// assert!(flags.contains(MethodAccessFlags::STATIC));
    /// assert!(!flags.contains(MethodAccessFlags::PRIVATE));
    ///
    /// // trigger derive Debug, Clone, Copy, PartialEq, Eq
    /// let cloned = flags.clone();
    /// assert_eq!(flags, cloned);
    /// format!("{:?}", flags);
    /// ```
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct MethodAccessFlags: u16 {
        /// Declared public; may be accessed from outside its package.
        const PUBLIC       = 0x0001;
        /// Declared private; accessible only within the defining class.
        const PRIVATE      = 0x0002;
        /// Declared protected; may be accessed within subclasses.
        const PROTECTED    = 0x0004;
        /// Declared static.
        const STATIC       = 0x0008;
        /// Declared final; must not be overridden (§5.4.5).
        const FINAL        = 0x0010;
        /// Declared synchronized; invocation is wrapped by a monitor use.
        const SYNCHRONIZED = 0x0020;
        /// A bridge method, generated by the compiler.
        const BRIDGE       = 0x0040;
        /// Declared with variable number of arguments.
        const VARARGS      = 0x0080;
        /// Declared native; implemented in a language other than Java.
        const NATIVE       = 0x0100;
        /// Declared abstract; no implementation is provided.
        const ABSTRACT     = 0x0400;
        /// Declared strictfp; floating-point mode is FP-strict.
        const STRICT       = 0x0800;
        /// Declared synthetic; not present in the source code.
        const SYNTHETIC    = 0x1000;
    }
}
