//! JSON Export tests for `TelemetryStore`
//!
//! This module verifies the JSON serialization paths in `TelemetryStore`, ensuring
//! that all channels and their custom serialization logic (e.g. `keyed_map`, `sorted_set`)
//! are properly executed and do not panic or fail.

#![allow(missing_docs)]

use duke_telemetry::TelemetryStore;

#[test]
#[cfg(feature = "telemetry")]
fn test_full_telemetry_store_json_export() {
    let mut store = TelemetryStore::default();

    // 1. Bytecode Cost
    store
        .bytecode_cost
        .record("iadd", "java/lang/Math", "add", 10, 500);

    // 2. Object Lineage
    store.object_lineage.record(
        "java/lang/String",
        "java/lang/StringBuilder",
        42,
        "toString",
    );

    // 3. Class Init DAG
    store
        .class_init_dag
        .record("java/lang/String", "java/lang/System", 1500);

    // 4. Exception Flow
    let throw_idx = store.exception_flow.record_throw(
        "java/io/IOException",
        "java/io/FileInputStream",
        "open",
        25,
    );
    store
        .exception_flow
        .record_catch(throw_idx, "java/util/Scanner", "read", 40);

    // 5. Dispatch Resolution
    store
        .dispatch_resolution
        .record("java/util/List", 10, "java/util/ArrayList", false);
    store
        .dispatch_resolution
        .record("java/util/List", 10, "java/util/LinkedList", false);

    // 6. Native Boundary
    store
        .native_boundary
        .record_call("java/lang/Object", "clone", 100, false);
    store
        .native_boundary
        .record_call("java/lang/System", "arraycopy", 250, true);

    let json_str = store.to_json();

    // Verification - verify top level keys
    assert!(json_str.contains("\"bytecode_cost\":"));
    assert!(json_str.contains("\"object_lineage\":"));
    assert!(json_str.contains("\"class_init_dag\":"));
    assert!(json_str.contains("\"exception_flow\":"));
    assert!(json_str.contains("\"dispatch_resolution\":"));
    assert!(json_str.contains("\"native_boundary\":"));

    // Verification - verify specific formatting outputs generated by `helpers::ser_helpers`

    // pair_str (BytecodeCostStore.by_site)
    assert!(json_str.contains("\"java/lang/Math::add@10\":"));

    // site3 (ObjectLineageStore.allocations)
    assert!(json_str.contains("\"java/lang/String::java/lang/StringBuilder@42\":"));

    // sorted_set (ClassInitDagStore.events)
    // Wait, the DAG doesn't use sorted set directly? Yes it does for causes.
    // Actually, DAG serialization might not directly use the custom serde helpers for the whole DAG,
    // but exception_flow or dispatch_resolution definitely uses site2_u16
    assert!(json_str.contains("\"java/io/IOException\""));
    assert!(json_str.contains("\"open\""));

    // site2_u16 (DispatchResolutionStore.by_site)
    assert!(json_str.contains("\"java/util/List@10\":"));

    // sorted_set (DispatchResolutionStore DispatchStat.unique_targets)
    assert!(json_str.contains("\"java/util/ArrayList\""));
    assert!(json_str.contains("\"java/util/LinkedList\""));

    // pair_str (NativeBoundaryStore.by_method)
    assert!(json_str.contains("\"java/lang/System::arraycopy\":"));
    assert!(json_str.contains("\"java/lang/Object::clone\":"));
}

#[test]
#[cfg(feature = "telemetry")]
fn test_empty_telemetry_store_json_export() {
    let store = TelemetryStore::default();
    let json_str = store.to_json();
    assert!(json_str.contains("\"bytecode_cost\""));
    assert!(json_str.contains("\"object_lineage\""));
    // Ensure it doesn't fail with empty HashMaps
}
