//! Bytecode Assembler for generating JVM instructions.
//!
//! This module provides a basic assembler to encode our `Instruction` enum
//! back into raw bytes. This enables dynamic generation of bytecode, which
//! could be used for testing, synthetic method generation, or future
//! bytecode instrumentation tools.

#[cfg(feature = "nova")]
use crate::Instruction;
#[cfg(feature = "nova")]
use crate::opcodes;

/// A simple assembler that emits raw JVM bytecode from `Instruction` objects.
///
/// It maintains a buffer of generated bytes. It allows you to build a method's
/// `Code` attribute dynamically without needing to write raw opcodes manually.
///
/// # Examples
///
/// ```
/// # #[cfg(feature = "nova")] {
/// use duke_bytecode::Assembler;
/// use duke_bytecode::Instruction;
///
/// let mut asm = Assembler::new();
/// asm.emit(&Instruction::Iconst0);
/// asm.emit(&Instruction::Ireturn);
///
/// let code = asm.finalize();
/// assert_eq!(code, vec![0x03, 0xac]); // iconst_0 (3), ireturn (172)
/// # }
/// ```
#[cfg(feature = "nova")]
#[derive(Debug, Default)]
pub struct Assembler {
    bytes: Vec<u8>,
}

#[cfg(feature = "nova")]
impl Assembler {
    /// Creates a new, empty assembler.
    #[must_use]
    pub const fn new() -> Self {
        Self { bytes: Vec::new() }
    }

    /// Emits a single instruction into the buffer.
    ///
    /// Currently supports a limited subset of instructions to demonstrate
    /// the capability (constants, basic returns, gotos).
    ///
    /// # Panics
    /// Panics if an unsupported instruction is passed.
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    pub fn emit(&mut self, instr: &Instruction) {
        match *instr {
            Instruction::Nop => self.bytes.push(opcodes::NOP),
            Instruction::AconstNull => self.bytes.push(opcodes::ACONST_NULL),
            Instruction::IconstM1 => self.bytes.push(opcodes::ICONST_M1),
            Instruction::Iconst0 => self.bytes.push(opcodes::ICONST_0),
            Instruction::Iconst1 => self.bytes.push(opcodes::ICONST_1),
            Instruction::Iconst2 => self.bytes.push(opcodes::ICONST_2),
            Instruction::Iconst3 => self.bytes.push(opcodes::ICONST_3),
            Instruction::Iconst4 => self.bytes.push(opcodes::ICONST_4),
            Instruction::Iconst5 => self.bytes.push(opcodes::ICONST_5),
            Instruction::Lconst0 => self.bytes.push(opcodes::LCONST_0),
            Instruction::Lconst1 => self.bytes.push(opcodes::LCONST_1),
            Instruction::Fconst0 => self.bytes.push(opcodes::FCONST_0),
            Instruction::Fconst1 => self.bytes.push(opcodes::FCONST_1),
            Instruction::Fconst2 => self.bytes.push(opcodes::FCONST_2),
            Instruction::Dconst0 => self.bytes.push(opcodes::DCONST_0),
            Instruction::Dconst1 => self.bytes.push(opcodes::DCONST_1),
            Instruction::Bipush(val) => {
                self.bytes.push(opcodes::BIPUSH);
                self.bytes.push(val as u8);
            }
            Instruction::Sipush(val) => {
                self.bytes.push(opcodes::SIPUSH);
                self.bytes.extend_from_slice(&val.to_be_bytes());
            }
            Instruction::Ldc(idx) => {
                self.bytes.push(opcodes::LDC);
                self.bytes.push(idx);
            }
            Instruction::LdcW(idx) => {
                self.bytes.push(opcodes::LDC_W);
                self.bytes.extend_from_slice(&idx.0.to_be_bytes());
            }
            Instruction::Ldc2W(idx) => {
                self.bytes.push(opcodes::LDC2_W);
                self.bytes.extend_from_slice(&idx.0.to_be_bytes());
            }
            Instruction::Ireturn => self.bytes.push(opcodes::IRETURN),
            Instruction::Lreturn => self.bytes.push(opcodes::LRETURN),
            Instruction::Freturn => self.bytes.push(opcodes::FRETURN),
            Instruction::Dreturn => self.bytes.push(opcodes::DRETURN),
            Instruction::Areturn => self.bytes.push(opcodes::ARETURN),
            Instruction::Return => self.bytes.push(opcodes::RETURN),
            Instruction::Goto(offset) => {
                self.bytes.push(opcodes::GOTO);
                self.bytes.extend_from_slice(&offset.to_be_bytes());
            }
            Instruction::Iadd => self.bytes.push(opcodes::IADD),
            Instruction::Ladd => self.bytes.push(opcodes::LADD),
            Instruction::Fadd => self.bytes.push(opcodes::FADD),
            Instruction::Dadd => self.bytes.push(opcodes::DADD),
            _ => panic!("Assembler does not yet support emitting: {instr:?}"),
        }
    }

    /// Emits raw bytes directly into the buffer.
    pub fn emit_raw(&mut self, opcode: u8, operands: &[u8]) {
        self.bytes.push(opcode);
        self.bytes.extend_from_slice(operands);
    }

    /// Returns the finalized vector of bytecodes.
    #[must_use]
    pub fn finalize(self) -> Vec<u8> {
        self.bytes
    }
}

#[cfg(test)]
#[cfg(feature = "nova")]
mod assembler_tests {
    use super::*;
    use crate::Instruction;

    #[test]
    fn test_assembler_constants() {
        let mut asm = Assembler::new();
        asm.emit(&Instruction::Iconst0);
        asm.emit(&Instruction::Bipush(42));
        asm.emit(&Instruction::Sipush(1000));
        asm.emit(&Instruction::Ireturn);

        let code = asm.finalize();
        assert_eq!(
            code,
            vec![
                0x03, // iconst_0
                0x10, 42, // bipush 42
                0x11, 0x03, 0xe8, // sipush 1000
                0xac  // ireturn
            ]
        );
    }

    #[test]
    fn test_assembler_goto() {
        let mut asm = Assembler::new();
        asm.emit(&Instruction::Goto(5));

        let code = asm.finalize();
        assert_eq!(
            code,
            vec![
                0xa7, 0x00, 0x05 // goto +5
            ]
        );
    }
}
