//! Typed JVM instruction representation.
//!
//! Each [`Instruction`] variant carries exactly the operands decoded from
//! the bytecode stream. The variant names match the JVM spec opcode names
//! (`PascalCase`). Wide-prefixed forms carry a `u16` local index instead of `u8`.

use duke_classfile::CpIndex;

/// Array type codes used by the `newarray` instruction (JVM spec §6.5).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArrayType {
    Boolean = 4,
    Char = 5,
    Float = 6,
    Double = 7,
    Byte = 8,
    Short = 9,
    Int = 10,
    Long = 11,
}

impl ArrayType {
    #[must_use]
    pub const fn from_u8(v: u8) -> Option<Self> {
        Some(match v {
            4 => Self::Boolean,
            5 => Self::Char,
            6 => Self::Float,
            7 => Self::Double,
            8 => Self::Byte,
            9 => Self::Short,
            10 => Self::Int,
            11 => Self::Long,
            _ => return None,
        })
    }
}

/// A single decoded JVM instruction with its operands.
///
/// Wide-prefixed variants (e.g., `IloadW`) are represented as distinct variants
/// so callers can exhaustively match without needing to track a separate `wide` flag.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Instruction {
    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------
    Nop,
    AconstNull,
    IconstM1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Lconst0,
    Lconst1,
    Fconst0,
    Fconst1,
    Fconst2,
    Dconst0,
    Dconst1,
    Bipush(i8),
    Sipush(i16),
    Ldc(u8),
    LdcW(CpIndex),
    Ldc2W(CpIndex),

    // -----------------------------------------------------------------------
    // Loads
    // -----------------------------------------------------------------------
    Iload(u8),
    Lload(u8),
    Fload(u8),
    Dload(u8),
    Aload(u8),
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Iaload,
    Laload,
    Faload,
    Daload,
    Aaload,
    Baload,
    Caload,
    Saload,

    // -----------------------------------------------------------------------
    // Stores
    // -----------------------------------------------------------------------
    Istore(u8),
    Lstore(u8),
    Fstore(u8),
    Dstore(u8),
    Astore(u8),
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Iastore,
    Lastore,
    Fastore,
    Dastore,
    Aastore,
    Bastore,
    Castore,
    Sastore,

    // -----------------------------------------------------------------------
    // Stack
    // -----------------------------------------------------------------------
    Pop,
    Pop2,
    Dup,
    DupX1,
    DupX2,
    Dup2,
    Dup2X1,
    Dup2X2,
    Swap,

    // -----------------------------------------------------------------------
    // Arithmetic
    // -----------------------------------------------------------------------
    Iadd,
    Ladd,
    Fadd,
    Dadd,
    Isub,
    Lsub,
    Fsub,
    Dsub,
    Imul,
    Lmul,
    Fmul,
    Dmul,
    Idiv,
    Ldiv,
    Fdiv,
    Ddiv,
    Irem,
    Lrem,
    Frem,
    Drem,
    Ineg,
    Lneg,
    Fneg,
    Dneg,
    Ishl,
    Lshl,
    Ishr,
    Lshr,
    Iushr,
    Lushr,
    Iand,
    Land,
    Ior,
    Lor,
    Ixor,
    Lxor,
    /// `iinc index const` — increment local by constant.
    Iinc {
        index: u8,
        value: i8,
    },

    // -----------------------------------------------------------------------
    // Conversions
    // -----------------------------------------------------------------------
    I2l,
    I2f,
    I2d,
    L2i,
    L2f,
    L2d,
    F2i,
    F2l,
    F2d,
    D2i,
    D2l,
    D2f,
    I2b,
    I2c,
    I2s,

    // -----------------------------------------------------------------------
    // Comparisons
    // -----------------------------------------------------------------------
    Lcmp,
    Fcmpl,
    Fcmpg,
    Dcmpl,
    Dcmpg,

    // -----------------------------------------------------------------------
    // Branches — offset is relative to the PC of this instruction
    // -----------------------------------------------------------------------
    Ifeq(i16),
    Ifne(i16),
    Iflt(i16),
    Ifge(i16),
    Ifgt(i16),
    Ifle(i16),
    IfIcmpeq(i16),
    IfIcmpne(i16),
    IfIcmplt(i16),
    IfIcmpge(i16),
    IfIcmpgt(i16),
    IfIcmple(i16),
    IfAcmpeq(i16),
    IfAcmpne(i16),
    Goto(i16),
    Jsr(i16),
    Ret(u8),
    Tableswitch {
        default: i32,
        low: i32,
        high: i32,
        offsets: Vec<i32>,
    },
    Lookupswitch {
        default: i32,
        pairs: Vec<(i32, i32)>, // (match_value, offset)
    },

    // -----------------------------------------------------------------------
    // Returns
    // -----------------------------------------------------------------------
    Ireturn,
    Lreturn,
    Freturn,
    Dreturn,
    Areturn,
    Return,

    // -----------------------------------------------------------------------
    // Field access
    // -----------------------------------------------------------------------
    Getstatic(CpIndex),
    Putstatic(CpIndex),
    Getfield(CpIndex),
    Putfield(CpIndex),

    // -----------------------------------------------------------------------
    // Method invocation
    // -----------------------------------------------------------------------
    Invokevirtual(CpIndex),
    Invokespecial(CpIndex),
    Invokestatic(CpIndex),
    /// `invokeinterface index count` — `count` is the number of arguments.
    Invokeinterface {
        index: CpIndex,
        count: u8,
    },
    Invokedynamic(CpIndex),

    // -----------------------------------------------------------------------
    // Object / array
    // -----------------------------------------------------------------------
    New(CpIndex),
    Newarray(ArrayType),
    Anewarray(CpIndex),
    Arraylength,
    Athrow,
    Checkcast(CpIndex),
    Instanceof(CpIndex),
    Monitorenter,
    Monitorexit,

    // -----------------------------------------------------------------------
    // Extended
    // -----------------------------------------------------------------------
    Multianewarray {
        index: CpIndex,
        dimensions: u8,
    },
    Ifnull(i16),
    Ifnonnull(i16),
    GotoW(i32),
    JsrW(i32),

    // -----------------------------------------------------------------------
    // Wide-prefixed variants (u16 index instead of u8)
    // -----------------------------------------------------------------------
    IloadW(u16),
    LloadW(u16),
    FloadW(u16),
    DloadW(u16),
    AloadW(u16),
    IstoreW(u16),
    LstoreW(u16),
    FstoreW(u16),
    DstoreW(u16),
    AstoreW(u16),
    RetW(u16),
    IincW {
        index: u16,
        value: i16,
    },
}

impl Instruction {
    /// Returns the mnemonic string for display/debugging.
    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub const fn mnemonic(&self) -> &'static str {
        match self {
            Self::Nop => "nop",
            Self::AconstNull => "aconst_null",
            Self::IconstM1 => "iconst_m1",
            Self::Iconst0 => "iconst_0",
            Self::Iconst1 => "iconst_1",
            Self::Iconst2 => "iconst_2",
            Self::Iconst3 => "iconst_3",
            Self::Iconst4 => "iconst_4",
            Self::Iconst5 => "iconst_5",
            Self::Lconst0 => "lconst_0",
            Self::Lconst1 => "lconst_1",
            Self::Fconst0 => "fconst_0",
            Self::Fconst1 => "fconst_1",
            Self::Fconst2 => "fconst_2",
            Self::Dconst0 => "dconst_0",
            Self::Dconst1 => "dconst_1",
            Self::Bipush(_) => "bipush",
            Self::Sipush(_) => "sipush",
            Self::Ldc(_) => "ldc",
            Self::LdcW(_) => "ldc_w",
            Self::Ldc2W(_) => "ldc2_w",
            Self::Iload(_) => "iload",
            Self::Lload(_) => "lload",
            Self::Fload(_) => "fload",
            Self::Dload(_) => "dload",
            Self::Aload(_) => "aload",
            Self::Iload0 => "iload_0",
            Self::Iload1 => "iload_1",
            Self::Iload2 => "iload_2",
            Self::Iload3 => "iload_3",
            Self::Lload0 => "lload_0",
            Self::Lload1 => "lload_1",
            Self::Lload2 => "lload_2",
            Self::Lload3 => "lload_3",
            Self::Fload0 => "fload_0",
            Self::Fload1 => "fload_1",
            Self::Fload2 => "fload_2",
            Self::Fload3 => "fload_3",
            Self::Dload0 => "dload_0",
            Self::Dload1 => "dload_1",
            Self::Dload2 => "dload_2",
            Self::Dload3 => "dload_3",
            Self::Aload0 => "aload_0",
            Self::Aload1 => "aload_1",
            Self::Aload2 => "aload_2",
            Self::Aload3 => "aload_3",
            Self::Iaload => "iaload",
            Self::Laload => "laload",
            Self::Faload => "faload",
            Self::Daload => "daload",
            Self::Aaload => "aaload",
            Self::Baload => "baload",
            Self::Caload => "caload",
            Self::Saload => "saload",
            Self::Istore(_) => "istore",
            Self::Lstore(_) => "lstore",
            Self::Fstore(_) => "fstore",
            Self::Dstore(_) => "dstore",
            Self::Astore(_) => "astore",
            Self::Istore0 => "istore_0",
            Self::Istore1 => "istore_1",
            Self::Istore2 => "istore_2",
            Self::Istore3 => "istore_3",
            Self::Lstore0 => "lstore_0",
            Self::Lstore1 => "lstore_1",
            Self::Lstore2 => "lstore_2",
            Self::Lstore3 => "lstore_3",
            Self::Fstore0 => "fstore_0",
            Self::Fstore1 => "fstore_1",
            Self::Fstore2 => "fstore_2",
            Self::Fstore3 => "fstore_3",
            Self::Dstore0 => "dstore_0",
            Self::Dstore1 => "dstore_1",
            Self::Dstore2 => "dstore_2",
            Self::Dstore3 => "dstore_3",
            Self::Astore0 => "astore_0",
            Self::Astore1 => "astore_1",
            Self::Astore2 => "astore_2",
            Self::Astore3 => "astore_3",
            Self::Iastore => "iastore",
            Self::Lastore => "lastore",
            Self::Fastore => "fastore",
            Self::Dastore => "dastore",
            Self::Aastore => "aastore",
            Self::Bastore => "bastore",
            Self::Castore => "castore",
            Self::Sastore => "sastore",
            Self::Pop => "pop",
            Self::Pop2 => "pop2",
            Self::Dup => "dup",
            Self::DupX1 => "dup_x1",
            Self::DupX2 => "dup_x2",
            Self::Dup2 => "dup2",
            Self::Dup2X1 => "dup2_x1",
            Self::Dup2X2 => "dup2_x2",
            Self::Swap => "swap",
            Self::Iadd => "iadd",
            Self::Ladd => "ladd",
            Self::Fadd => "fadd",
            Self::Dadd => "dadd",
            Self::Isub => "isub",
            Self::Lsub => "lsub",
            Self::Fsub => "fsub",
            Self::Dsub => "dsub",
            Self::Imul => "imul",
            Self::Lmul => "lmul",
            Self::Fmul => "fmul",
            Self::Dmul => "dmul",
            Self::Idiv => "idiv",
            Self::Ldiv => "ldiv",
            Self::Fdiv => "fdiv",
            Self::Ddiv => "ddiv",
            Self::Irem => "irem",
            Self::Lrem => "lrem",
            Self::Frem => "frem",
            Self::Drem => "drem",
            Self::Ineg => "ineg",
            Self::Lneg => "lneg",
            Self::Fneg => "fneg",
            Self::Dneg => "dneg",
            Self::Ishl => "ishl",
            Self::Lshl => "lshl",
            Self::Ishr => "ishr",
            Self::Lshr => "lshr",
            Self::Iushr => "iushr",
            Self::Lushr => "lushr",
            Self::Iand => "iand",
            Self::Land => "land",
            Self::Ior => "ior",
            Self::Lor => "lor",
            Self::Ixor => "ixor",
            Self::Lxor => "lxor",
            Self::Iinc { .. } => "iinc",
            Self::I2l => "i2l",
            Self::I2f => "i2f",
            Self::I2d => "i2d",
            Self::L2i => "l2i",
            Self::L2f => "l2f",
            Self::L2d => "l2d",
            Self::F2i => "f2i",
            Self::F2l => "f2l",
            Self::F2d => "f2d",
            Self::D2i => "d2i",
            Self::D2l => "d2l",
            Self::D2f => "d2f",
            Self::I2b => "i2b",
            Self::I2c => "i2c",
            Self::I2s => "i2s",
            Self::Lcmp => "lcmp",
            Self::Fcmpl => "fcmpl",
            Self::Fcmpg => "fcmpg",
            Self::Dcmpl => "dcmpl",
            Self::Dcmpg => "dcmpg",
            Self::Ifeq(_) => "ifeq",
            Self::Ifne(_) => "ifne",
            Self::Iflt(_) => "iflt",
            Self::Ifge(_) => "ifge",
            Self::Ifgt(_) => "ifgt",
            Self::Ifle(_) => "ifle",
            Self::IfIcmpeq(_) => "if_icmpeq",
            Self::IfIcmpne(_) => "if_icmpne",
            Self::IfIcmplt(_) => "if_icmplt",
            Self::IfIcmpge(_) => "if_icmpge",
            Self::IfIcmpgt(_) => "if_icmpgt",
            Self::IfIcmple(_) => "if_icmple",
            Self::IfAcmpeq(_) => "if_acmpeq",
            Self::IfAcmpne(_) => "if_acmpne",
            Self::Goto(_) => "goto",
            Self::Jsr(_) => "jsr",
            Self::Ret(_) => "ret",
            Self::Tableswitch { .. } => "tableswitch",
            Self::Lookupswitch { .. } => "lookupswitch",
            Self::Ireturn => "ireturn",
            Self::Lreturn => "lreturn",
            Self::Freturn => "freturn",
            Self::Dreturn => "dreturn",
            Self::Areturn => "areturn",
            Self::Return => "return",
            Self::Getstatic(_) => "getstatic",
            Self::Putstatic(_) => "putstatic",
            Self::Getfield(_) => "getfield",
            Self::Putfield(_) => "putfield",
            Self::Invokevirtual(_) => "invokevirtual",
            Self::Invokespecial(_) => "invokespecial",
            Self::Invokestatic(_) => "invokestatic",
            Self::Invokeinterface { .. } => "invokeinterface",
            Self::Invokedynamic(_) => "invokedynamic",
            Self::New(_) => "new",
            Self::Newarray(_) => "newarray",
            Self::Anewarray(_) => "anewarray",
            Self::Arraylength => "arraylength",
            Self::Athrow => "athrow",
            Self::Checkcast(_) => "checkcast",
            Self::Instanceof(_) => "instanceof",
            Self::Monitorenter => "monitorenter",
            Self::Monitorexit => "monitorexit",
            Self::Multianewarray { .. } => "multianewarray",
            Self::Ifnull(_) => "ifnull",
            Self::Ifnonnull(_) => "ifnonnull",
            Self::GotoW(_) => "goto_w",
            Self::JsrW(_) => "jsr_w",
            Self::IloadW(_) => "wide iload",
            Self::LloadW(_) => "wide lload",
            Self::FloadW(_) => "wide fload",
            Self::DloadW(_) => "wide dload",
            Self::AloadW(_) => "wide aload",
            Self::IstoreW(_) => "wide istore",
            Self::LstoreW(_) => "wide lstore",
            Self::FstoreW(_) => "wide fstore",
            Self::DstoreW(_) => "wide dstore",
            Self::AstoreW(_) => "wide astore",
            Self::RetW(_) => "wide ret",
            Self::IincW { .. } => "wide iinc",
        }
    }
}
