//! Repositories for loaded classes and registered native methods.
//!
//! Provides the execution environment with access to classes, handles class loading and
//! initialization on demand, and maintains the mapping between `native` methods
//! and their Rust implementations.

use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::path::Path;
use std::sync::Arc;

use duke_loader::ClassLoader;
use duke_runtime::{Error, Result, Slot};

use crate::context::ClassContext;

fn class_internal_name_fragment(name: &str) -> &str {
    name.split_once('\0')
        .map_or(name, |(internal_name, _)| internal_name)
}

/// Metadata for a lambda proxy object created by `LambdaMetafactory`.
///
/// When the JVM encounters an `invokedynamic` instruction targeting `LambdaMetafactory`,
/// it doesn't just call a method. It dynamically generates a synthetic class at runtime that
/// implements the required functional interface. This struct holds the "blueprint" for that
/// synthetic class.
///
/// It acts as the bridge connecting the Single Abstract Method (SAM) the interface expects
/// to the actual implementation method containing the lambda body.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::LambdaInfo;
///
/// let info = LambdaInfo {
///     impl_class: "java/lang/invoke/LambdaMetafactory".to_string(),
///     impl_method: "lambda$main$0".to_string(),
///     impl_desc: "()V".to_string(),
///     impl_kind: 6, // REF_invokeStatic
///     sam_method: "run".to_string(),
///     sam_desc: "()V".to_string(),
///     sam_interface: "java/lang/Runnable".to_string(),
///     captured_count: 0,
/// };
/// ```
#[derive(Debug, Clone)]
pub struct LambdaInfo {
    /// The target implementation class generated by the VM (e.g. `java/lang/invoke/LambdaMetafactory`).
    pub impl_class: String,
    /// The physical method implementing the lambda body.
    pub impl_method: String,
    /// The physical method descriptor implementing the lambda body.
    pub impl_desc: String,
    /// Method handle kind detailing how the implementation should be invoked.
    pub impl_kind: u8,
    /// The name of the Single Abstract Method (SAM) defined by the functional interface.
    pub sam_method: String,
    /// The JVM descriptor of the SAM defined by the functional interface.
    pub sam_desc: String,
    /// Functional interface this lambda implements, e.g. "java/util/function/Function".
    pub sam_interface: String,
    /// The number of arguments captured from the surrounding lexical scope.
    pub captured_count: usize,
}

/// Threading side-channel requested by a native handler.
///
/// Native methods execute within the same Rust thread as the interpreter loop. When a Java thread
/// needs to block (e.g. `Thread.sleep`) or fork (e.g. `Thread.start`), the native method cannot
/// perform the action directly without blocking or panicking the interpreter. Instead, it requests
/// an action and returns to the loop to be processed safely.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::{NativeControl, NativeThreadAction};
///
/// let mut control = NativeControl::default();
/// control.request(NativeThreadAction::Sleep(std::time::Duration::from_millis(100)));
///
/// assert_eq!(control.take(), Some(NativeThreadAction::Sleep(std::time::Duration::from_millis(100))));
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeThreadAction {
    /// Start a new thread execution context for the given Java thread object.
    Start {
        /// The heap reference to the `java/lang/Thread` instance to start.
        thread_ref: u64,
    },
    /// Suspend the current thread for the specified duration.
    Sleep(std::time::Duration),
    /// Suspend the current thread until the target thread terminates.
    Join {
        /// The native thread ID of the thread to wait for.
        thread_id: i32,
    },
}

/// One Java-frame snapshot made available to native handlers that need to
/// materialize stack traces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativeStackFrame {
    /// Internal JVM class name, e.g. `com/example/Main`.
    pub class_name: String,
    /// JVM method name, e.g. `main` or `lambda$run$0`.
    pub method_name: String,
    /// Optional source file from the class-level `SourceFile` attribute.
    pub file_name: Option<String>,
    /// Java source line, `-1` when unknown and `-2` for native methods.
    pub line_number: i32,
}

/// Per-invocation control state for native handlers.
#[derive(Debug, Default)]
pub struct NativeControl {
    pending_thread_action: Option<NativeThreadAction>,
    stack_trace: Vec<NativeStackFrame>,
}

impl NativeControl {
    /// Request a thread-related action from the interpreter loop.
    pub const fn request(&mut self, action: NativeThreadAction) {
        self.pending_thread_action = Some(action);
    }

    /// Take the pending thread-related action, if any.
    pub const fn take(&mut self) -> Option<NativeThreadAction> {
        self.pending_thread_action.take()
    }

    /// Attach a stack snapshot to this native invocation.
    pub fn set_stack_trace(&mut self, stack_trace: Vec<NativeStackFrame>) {
        self.stack_trace = stack_trace;
    }

    /// Read the stack snapshot for this native invocation.
    #[must_use]
    pub fn stack_trace(&self) -> &[NativeStackFrame] {
        &self.stack_trace
    }
}

/// Reflection metadata for one declared method discovered from a classfile.
///
/// This provides the native reflection system (like `java/lang/reflect/Method`)
/// access to a method's raw details.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::ReflectedMethodInfo;
///
/// let info = ReflectedMethodInfo {
///     name: "toString".to_string(),
///     descriptor: "()Ljava/lang/String;".to_string(),
///     is_public: true,
///     is_static: false,
///     annotations: vec![],
///     annotation_default: None,
/// };
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct ReflectedMethodInfo {
    /// The exact string name of the method (e.g. `"toString"`).
    pub name: String,
    /// The JVM type descriptor (e.g. `"()V"`).
    pub descriptor: String,
    /// True if the method has the `ACC_PUBLIC` modifier.
    pub is_public: bool,
    /// True if the method has the `ACC_STATIC` modifier.
    pub is_static: bool,
    /// Runtime-visible annotations declared directly on the method.
    pub annotations: Vec<ReflectedAnnotation>,
    /// Default element value when this method is an annotation element.
    pub annotation_default: Option<ReflectedAnnotationValue>,
}

/// Reflection metadata for one declared field discovered from a classfile.
///
/// This provides the native reflection system (like `java/lang/reflect/Field`)
/// access to a field's raw details.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::ReflectedFieldInfo;
///
/// let info = ReflectedFieldInfo {
///     name: "count".to_string(),
///     descriptor: "I".to_string(),
///     is_public: false,
///     is_static: true,
///     annotations: vec![],
/// };
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct ReflectedFieldInfo {
    /// The exact string name of the field.
    pub name: String,
    /// The JVM type descriptor.
    pub descriptor: String,
    /// True if the field has the `ACC_PUBLIC` modifier.
    pub is_public: bool,
    /// True if the field has the `ACC_STATIC` modifier.
    pub is_static: bool,
    /// Runtime-visible annotations declared directly on the field.
    pub annotations: Vec<ReflectedAnnotation>,
}

/// Runtime-visible annotation metadata with constant-pool indices resolved.
#[derive(Debug, Clone, PartialEq)]
pub struct ReflectedAnnotation {
    /// Annotation interface internal name, e.g. `com/example/Route`.
    pub type_name: String,
    /// Explicitly configured element values on this annotation usage.
    pub elements: Vec<ReflectedAnnotationElement>,
}

/// One named annotation element value.
#[derive(Debug, Clone, PartialEq)]
pub struct ReflectedAnnotationElement {
    /// Element method name.
    pub name: String,
    /// Parsed element value.
    pub value: ReflectedAnnotationValue,
}

/// Parsed annotation element value ready for runtime materialization.
#[derive(Debug, Clone, PartialEq)]
pub enum ReflectedAnnotationValue {
    /// Primitive or `String` constant.
    Const(ReflectedAnnotationConst),
    /// Enum constant, stored as enum type internal name and constant name.
    Enum {
        /// The internal name of the enum type (e.g., `java/lang/annotation/RetentionPolicy`).
        type_name: String,
        /// The exact string name of the enum constant (e.g., `RUNTIME`).
        const_name: String,
    },
    /// Class literal internal name or primitive descriptor.
    Class(String),
    /// Nested annotation.
    Annotation(Box<ReflectedAnnotation>),
    /// Array of annotation values.
    Array(Vec<Self>),
}

/// Primitive and `String` annotation constants.
///
/// This enum represents all possible primitive and `String` constant values
/// that can be embedded directly within a Java annotation element. They are
/// mapped from the raw classfile constant pool into these owned Rust types
/// for easy runtime reflection access.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::ReflectedAnnotationConst;
///
/// let byte_val = ReflectedAnnotationConst::Byte(42);
/// let str_val = ReflectedAnnotationConst::String("Test".to_string());
/// ```
#[derive(Debug, Clone, PartialEq)]
pub enum ReflectedAnnotationConst {
    /// A `byte` constant, internally promoted to `i32` following JVM conventions.
    Byte(i32),
    /// A `char` constant, internally promoted to `i32` representing the UTF-16 code point.
    Char(i32),
    /// A 64-bit IEEE 754 floating-point `double` constant.
    Double(f64),
    /// A 32-bit IEEE 754 floating-point `float` constant.
    Float(f32),
    /// A 32-bit signed `int` constant.
    Int(i32),
    /// A 64-bit signed `long` constant.
    Long(i64),
    /// A `short` constant, internally promoted to `i32` following JVM conventions.
    Short(i32),
    /// A `boolean` constant, parsed from the integer `1` (true) or `0` (false) in the classfile.
    Boolean(bool),
    /// A resolved `java.lang.String` constant value.
    String(String),
}

/// Reflection metadata for one class discovered from the loader or registry.
///
/// This provides the native reflection system (`java/lang/Class`) access to a
/// loaded class's full hierarchy and declared members.
///
/// ## Examples
///
/// ```
/// use duke_interpreter::ReflectedClassInfo;
///
/// let info = ReflectedClassInfo {
///     internal_name: "java/lang/String".to_string(),
///     binary_name: "java.lang.String".to_string(),
///     super_class: Some("java/lang/Object".to_string()),
///     interfaces: vec!["java/io/Serializable".to_string()],
///     methods: vec![],
///     fields: vec![],
///     annotations: vec![],
/// };
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct ReflectedClassInfo {
    /// The raw JVM internal name (e.g. `"java/lang/Object"`).
    pub internal_name: String,
    /// The Java binary name (e.g. `"java.lang.Object"`).
    pub binary_name: String,
    /// The internal name of the superclass, if any (null for `Object`).
    pub super_class: Option<String>,
    /// The internal names of all directly implemented interfaces.
    pub interfaces: Vec<String>,
    /// All methods explicitly declared by this class (excluding inherited).
    pub methods: Vec<ReflectedMethodInfo>,
    /// All fields explicitly declared by this class (excluding inherited).
    pub fields: Vec<ReflectedFieldInfo>,
    /// Runtime-visible annotations declared directly on the class.
    pub annotations: Vec<ReflectedAnnotation>,
}
/// A registry managing loaded classes, their initialization state, and associated native methods.
pub struct ClassRegistry {
    classes: HashMap<String, ClassContext>,
    natives: NativeRegistry,
    /// Tracks which classes have had their `<clinit>` run.
    initialized: HashSet<String>,
    /// Lambda proxy class name → metadata.
    lambdas: HashMap<String, LambdaInfo>,
    /// Monotonic counter for generating unique lambda class names.
    lambda_counter: u64,
    /// Default code source path used for lightweight ``ProtectionDomain`` emulation.
    default_code_source: Option<String>,
    /// Path-backed class loaders (ZIP/JAR or directory) keyed by stable source path.
    archive_loaders: HashMap<String, Arc<dyn ClassLoader + Send + Sync>>,
    /// Best-known code source path for each loaded class.
    class_code_sources: HashMap<String, String>,
    /// Best-known runtime `java/lang/ClassLoader` object for each loaded class.
    class_runtime_loaders: HashMap<String, u64>,
    /// Storage for execution telemetry (e.g. instruction counts, GC pause times).
    ///
    /// The [`TelemetryStore`](duke_telemetry::TelemetryStore) collects performance metrics
    /// and usage statistics across the lifetime of the VM.
    #[cfg(feature = "telemetry")]
    pub telemetry: duke_telemetry::TelemetryStore,
}

impl ClassRegistry {
    /// Creates a new empty class registry.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// assert!(!registry.contains("MyClass"));
    /// ```
    #[must_use]
    pub fn new() -> Self {
        Self {
            classes: HashMap::new(),
            natives: NativeRegistry::new(),
            initialized: HashSet::new(),
            lambdas: HashMap::new(),
            lambda_counter: 0,
            default_code_source: None,
            archive_loaders: HashMap::new(),
            class_code_sources: HashMap::new(),
            class_runtime_loaders: HashMap::new(),
            #[cfg(feature = "telemetry")]
            telemetry: duke_telemetry::TelemetryStore::default(),
        }
    }

    pub(crate) fn register_lambda(&mut self, info: LambdaInfo) -> String {
        let name = format!("$$Lambda${}", self.lambda_counter);
        self.lambda_counter += 1;
        self.lambdas.insert(name.clone(), info);
        name
    }

    pub(crate) fn get_lambda(&self, class_name: &str) -> Option<&LambdaInfo> {
        self.lambdas.get(class_name)
    }

    /// Checks if a class has been successfully initialized (its `<clinit>` method has completed).
    ///
    /// This prevents the JVM from redundantly re-initializing the same class
    /// during subsequent method invocations or object instantiations.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// assert!(!registry.is_initialized("java/lang/String"));
    /// registry.mark_initialized("java/lang/String");
    /// assert!(registry.is_initialized("java/lang/String"));
    /// ```
    #[must_use]
    pub fn is_initialized(&self, name: &str) -> bool {
        self.initialized.contains(name)
    }

    /// Marks a class as fully initialized.
    ///
    /// Once a class's `<clinit>` method finishes successfully, the JVM calls this
    /// to record that the class is ready for use, skipping future initialization checks.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// registry.mark_initialized("java/util/List");
    /// assert!(registry.is_initialized("java/util/List"));
    /// ```
    pub fn mark_initialized(&mut self, name: &str) {
        self.initialized.insert(name.to_string());
    }

    /// Sets the fallback code source path for classes loaded by the VM.
    ///
    /// This is used primarily to furnish a `ProtectionDomain` for classes when
    /// explicit, per-class provenance tracking (e.g., loaded from a specific JAR)
    /// has not been recorded yet.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// registry.set_default_code_source("/usr/lib/jvm/rt.jar");
    /// assert_eq!(registry.default_code_source(), Some("/usr/lib/jvm/rt.jar"));
    /// ```
    pub fn set_default_code_source(&mut self, path: impl Into<String>) {
        self.default_code_source = Some(path.into());
    }

    /// Reads the globally configured fallback code source path, if one was set.
    ///
    /// Returns `None` if no default has been established.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// assert_eq!(registry.default_code_source(), None);
    /// registry.set_default_code_source("bootstrap.jar");
    /// assert_eq!(registry.default_code_source(), Some("bootstrap.jar"));
    /// ```
    #[must_use]
    pub fn default_code_source(&self) -> Option<&str> {
        self.default_code_source.as_deref()
    }

    /// Return the best-known code source path for `class`, if Duke has one.
    #[must_use]
    pub fn code_source_for_class(&self, class: &str) -> Option<&str> {
        self.class_code_sources
            .get(class)
            .map(String::as_str)
            .or_else(|| self.default_code_source())
    }

    /// Return the cached defining loader for `class`, if any.
    #[must_use]
    pub fn class_loader(&self, class: &str) -> Option<&Arc<dyn ClassLoader + Send + Sync>> {
        self.class_code_sources
            .get(class)
            .and_then(|path| self.archive_loaders.get(path))
    }

    /// Return the best-known runtime `java/lang/ClassLoader` object for `class`.
    #[must_use]
    pub fn runtime_loader_for_class(&self, class: &str) -> Option<u64> {
        self.class_runtime_loaders.get(class).copied()
    }

    /// Return the human-facing internal name for `class`, stripping any loader provenance.
    #[must_use]
    pub fn internal_name_for_class<'a>(&self, class: &'a str) -> &'a str {
        class_internal_name_fragment(class)
    }

    fn is_plain_bootstrap_class(&self, class: &str) -> bool {
        self.classes.contains_key(class)
            && !self.class_code_sources.contains_key(class)
            && !self.class_runtime_loaders.contains_key(class)
    }

    /// Compute the deterministic class identity key for a class reference under explicit provenance.
    #[must_use]
    pub fn class_key_from_provenance(
        &self,
        internal_name: &str,
        code_source: Option<&str>,
        runtime_loader: Option<u64>,
    ) -> String {
        let internal_name = class_internal_name_fragment(internal_name);
        if internal_name.starts_with('[')
            || internal_name.len() == 1
            || self.is_plain_bootstrap_class(internal_name)
        {
            return internal_name.to_string();
        }
        if let Some(loader_ref) = runtime_loader {
            return format!("{internal_name}\0loader:{loader_ref}");
        }
        if let Some(path) = code_source {
            return format!("{internal_name}\0code:{path}");
        }
        internal_name.to_string()
    }

    /// Compute the class identity key implied by the provenance of `source_class`.
    #[must_use]
    pub fn class_key_from_source(&self, internal_name: &str, source_class: Option<&str>) -> String {
        let code_source = source_class.and_then(|class| self.explicit_code_source_for_class(class));
        let runtime_loader = source_class.and_then(|class| self.runtime_loader_for_class(class));
        self.class_key_from_provenance(internal_name, code_source, runtime_loader)
    }

    #[must_use]
    fn explicit_code_source_for_class(&self, class: &str) -> Option<&str> {
        self.class_code_sources.get(class).map(String::as_str)
    }

    fn path_loader_for_path(&mut self, path: &str) -> Option<Arc<dyn ClassLoader + Send + Sync>> {
        if let Some(loader) = self.archive_loaders.get(path) {
            return Some(Arc::clone(loader));
        }
        let source_path = Path::new(path);
        let loader: Arc<dyn ClassLoader + Send + Sync> = if source_path.is_dir() {
            Arc::new(duke_loader::DirectoryLoader::new(source_path))
        } else {
            Arc::new(duke_loader::ZipLoader::open(source_path).ok()?)
        };
        self.archive_loaders
            .insert(path.to_string(), Arc::clone(&loader));
        Some(loader)
    }

    pub(crate) fn service_configuration_files_for_paths(
        &mut self,
        paths: &[String],
        service_binary_name: &str,
    ) -> Result<Vec<Vec<u8>>> {
        let mut files = Vec::new();
        for path in paths {
            let Some(loader) = self.path_loader_for_path(path) else {
                continue;
            };
            let mut path_files = loader
                .service_configuration_files(service_binary_name)
                .map_err(|_| Error::JavaException {
                    class_name: "java/util/ServiceConfigurationError".to_string(),
                })?;
            files.append(&mut path_files);
        }
        Ok(files)
    }

    /// Access the native method registry.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let registry = ClassRegistry::new();
    /// assert!(registry.natives().get("java/lang/System", "exit", "(I)V").is_none());
    /// ```
    #[must_use]
    pub const fn natives(&self) -> &NativeRegistry {
        &self.natives
    }

    /// Access the native method registry mutably.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    ///
    /// let mut registry = ClassRegistry::new();
    /// // registry.natives_mut().register(...)
    /// ```
    pub const fn natives_mut(&mut self) -> &mut NativeRegistry {
        &mut self.natives
    }

    /// Register a pre-built `ClassContext`.
    pub fn register(&mut self, ctx: ClassContext) {
        self.classes.insert(ctx.class_name.clone(), ctx);
    }

    /// Get a reference to a loaded class.
    ///
    /// # Errors
    /// Returns [`Error::ClassNotFound`] if the class is not loaded.
    pub fn get(&self, name: &str) -> Result<&ClassContext> {
        self.classes.get(name).ok_or_else(|| Error::ClassNotFound {
            name: name.to_string(),
        })
    }

    /// Get a mutable reference to a loaded class.
    ///
    /// # Errors
    /// Returns [`Error::ClassNotFound`] if the class is not loaded.
    pub fn get_mut(&mut self, name: &str) -> Result<&mut ClassContext> {
        self.classes
            .get_mut(name)
            .ok_or_else(|| Error::ClassNotFound {
                name: name.to_string(),
            })
    }

    /// Ensure a class is loaded into the registry.
    ///
    /// The JVM doesn't load classes until the exact moment they are needed (e.g., when a `new` instruction
    /// is executed, or a static method is invoked). This method handles that lazy loading process.
    ///
    /// If the class is not already present in the registry, it uses the provided `loader` to find the
    /// raw `.class` bytes, parses them, builds a [`ClassContext`], and registers it.
    ///
    /// Crucially, it recursively loads the entire superclass and interface chain. Why? Because the JVM
    /// needs to know the total size of all fields (including inherited ones) before it can safely allocate
    /// an object on the heap. Without this recursive loading, an instance of `Child` might overwrite the
    /// fields of its `Parent`!
    ///
    /// Returns `Ok(true)` if the class was successfully loaded, or `Ok(false)` if the class could not be found.
    /// A soft failure (`Ok(false)`) is used because core JDK classes (like `java/lang/Object`) might not
    /// be available yet during early bootstrap.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::ClassRegistry;
    /// use duke_loader::{ClassLoader, Result, Error};
    ///
    /// // Create a mock class loader that supplies bytes for `java/lang/Object`.
    /// struct MockLoader;
    /// impl ClassLoader for MockLoader {
    ///     fn find_class(&self, name: &str) -> Result<Vec<u8>> {
    ///         if name == "java/lang/Object" {
    ///             // Minimal valid classfile bytes for an empty class
    ///             Ok(vec![
    ///                 0xCA, 0xFE, 0xBA, 0xBE, 0x00, 0x00, 0x00, 0x34,
    ///                 0x00, 0x03, 0x07, 0x00, 0x02, 0x01, 0x00, 0x10,
    ///                 0x6A, 0x61, 0x76, 0x61, 0x2F, 0x6C, 0x61, 0x6E,
    ///                 0x67, 0x2F, 0x4F, 0x62, 0x6A, 0x65, 0x63, 0x74,
    ///                 0x00, 0x21, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
    ///                 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    ///             ])
    ///         } else {
    ///             Err(Error::NotFound { name: name.to_string() })
    ///         }
    ///     }
    /// }
    ///
    /// let mut registry = ClassRegistry::new();
    /// let loader = MockLoader;
    ///
    /// // Object is not loaded yet.
    /// assert!(!registry.contains("java/lang/Object"));
    ///
    /// // Lazily load the class and its superclasses on demand.
    /// let loaded = registry.ensure_loaded("java/lang/Object", &loader).unwrap();
    /// assert!(loaded);
    ///
    /// // The registry now holds the parsed and linked class context!
    /// assert!(registry.contains("java/lang/Object"));
    /// ```
    ///
    /// # Errors
    /// Returns [`Error`] if the class bytes are malformed or if loading the superclass chain fails unexpectedly.
    pub fn ensure_loaded(&mut self, name: &str, loader: &dyn ClassLoader) -> Result<bool> {
        self.ensure_loaded_inner(name, loader, None, None)
    }

    /// Ensure a class is loaded using the same archive/classpath provenance as `source_class`.
    ///
    /// # Errors
    /// Returns [`Error`] if the selected loader fails to parse, link, or resolve the requested class.
    pub fn ensure_loaded_from(
        &mut self,
        name: &str,
        source_class: Option<&str>,
        fallback_loader: &dyn ClassLoader,
    ) -> Result<bool> {
        if let Some(source_class) = source_class
            && let Some(path) = self
                .explicit_code_source_for_class(source_class)
                .map(ToOwned::to_owned)
        {
            return self.ensure_loaded_with_provenance(
                name,
                &path,
                self.runtime_loader_for_class(source_class),
            );
        }
        self.ensure_loaded(name, fallback_loader)
    }

    /// Ensure a class is loaded from a specific archive path and record that provenance.
    ///
    /// # Errors
    /// Returns [`Error`] if the selected archive loader fails to parse, link, or resolve the requested class.
    pub fn ensure_loaded_with_code_source(&mut self, name: &str, path: &str) -> Result<bool> {
        self.ensure_loaded_with_provenance(name, path, None)
    }

    /// Ensure a class is loaded from a specific archive path and runtime loader.
    ///
    /// # Errors
    /// Returns [`Error`] if the selected archive loader fails to parse, link, or resolve the requested class.
    pub fn ensure_loaded_with_provenance(
        &mut self,
        name: &str,
        path: &str,
        runtime_loader: Option<u64>,
    ) -> Result<bool> {
        let Some(loader) = self.path_loader_for_path(path) else {
            return Ok(false);
        };
        self.ensure_loaded_inner(name, loader.as_ref(), Some(path), runtime_loader)
    }

    fn ensure_loaded_inner(
        &mut self,
        name: &str,
        loader: &dyn ClassLoader,
        code_source: Option<&str>,
        runtime_loader: Option<u64>,
    ) -> Result<bool> {
        let internal_name = class_internal_name_fragment(name).to_string();
        let class_key = self.class_key_from_provenance(&internal_name, code_source, runtime_loader);
        if self.classes.contains_key(&class_key) {
            if let Some(path) = code_source {
                self.class_code_sources
                    .entry(class_key.clone())
                    .or_insert_with(|| path.to_string());
            }
            if let Some(loader_ref) = runtime_loader {
                self.class_runtime_loaders
                    .entry(class_key)
                    .or_insert(loader_ref);
            }
            return Ok(true);
        }
        let Ok(bytes) = loader.find_class(&internal_name) else {
            return Ok(false);
        };
        let Ok(cf) = duke_classfile::parse(&bytes) else {
            return Ok(false);
        };
        let mut ctx = crate::build_class_context(&cf);
        let resolved_super_class = if let Some(super_class) = &ctx.super_class {
            let _ = self.ensure_loaded_inner(super_class, loader, code_source, runtime_loader)?;
            Some(self.class_key_from_provenance(super_class, code_source, runtime_loader))
        } else {
            None
        };
        let mut resolved_interfaces = Vec::with_capacity(ctx.interfaces.len());
        for interface in &ctx.interfaces {
            let _ = self.ensure_loaded_inner(interface, loader, code_source, runtime_loader)?;
            resolved_interfaces.push(self.class_key_from_provenance(
                interface,
                code_source,
                runtime_loader,
            ));
        }
        ctx.class_name.clone_from(&class_key);
        ctx.super_class = resolved_super_class;
        ctx.interfaces = resolved_interfaces;
        self.classes.insert(class_key.clone(), ctx);
        if let Some(path) = code_source {
            self.class_code_sources
                .insert(class_key.clone(), path.to_string());
        }
        if let Some(loader_ref) = runtime_loader {
            self.class_runtime_loaders.insert(class_key, loader_ref);
        }
        Ok(true)
    }

    /// Check if a class is loaded.
    #[must_use]
    pub fn contains(&self, name: &str) -> bool {
        self.classes.contains_key(name)
    }

    /// Resolve `name` to an exact loaded class key.
    ///
    /// Accepts either an exact class key or a plain internal name when exactly one
    /// loaded class matches that internal name.
    ///
    /// # Errors
    /// Returns [`Error::ClassNotFound`] when no loaded class matches, or
    /// [`Error::AmbiguousClassName`] when multiple loaded classes share the same
    /// internal name.
    pub fn resolve_loaded_class_key(&self, name: &str) -> Result<String> {
        if self.classes.contains_key(name) {
            return Ok(name.to_string());
        }
        let internal_name = self.internal_name_for_class(name);
        let matches: Vec<String> = self
            .classes
            .keys()
            .filter(|class| self.internal_name_for_class(class) == internal_name)
            .cloned()
            .collect();
        match matches.as_slice() {
            [] => Err(Error::ClassNotFound {
                name: name.to_string(),
            }),
            [only] => Ok(only.clone()),
            _ => Err(Error::AmbiguousClassName {
                name: internal_name.to_string(),
                matches,
            }),
        }
    }

    /// Iterate all registered class contexts — used by GC root gathering.
    pub fn all_classes(&self) -> impl Iterator<Item = &ClassContext> {
        self.classes.values()
    }

    /// Mutably iterate all registered class contexts — used to patch static
    /// field slots after a minor GC collection.
    pub fn all_classes_mut(&mut self) -> impl Iterator<Item = &mut ClassContext> {
        self.classes.values_mut()
    }
}

impl Default for ClassRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Signature for native method implementations.
///
/// Arguments:
/// - `&[Slot]`: method arguments (including `this` in slot 0 for instance methods)
/// - `&mut Heap`: the object heap for reading/writing objects
/// - `&mut dyn Write`: output sink (stdout in production, `Vec<u8>` in tests)
/// - `&mut NativeControl`: side channel for blocking/thread actions
pub type NativeHandler =
    fn(&[Slot], &mut duke_gc::Heap, &mut dyn Write, &mut NativeControl) -> Result<Option<Slot>>;

/// Mutable helper surface exposed to callback natives.
///
/// This keeps class loading, reflection metadata inspection, and nested Java
/// invocation behind one mutable object so natives do not need direct access to
/// the interpreter's registry/loader state.
pub trait CallbackOps {
    /// Invoke a Java method through the current interpreter/runtime boundary.
    ///
    /// # Errors
    /// Returns any VM error produced while resolving or executing the target method.
    fn invoke(
        &mut self,
        heap: &mut duke_gc::Heap,
        output: &mut dyn Write,
        class: &str,
        method: &str,
        descriptor: &str,
        args: Vec<Slot>,
    ) -> Result<Option<Slot>>;

    /// Ensure the named class is available to the current runtime.
    ///
    /// # Errors
    /// Returns an error if the class cannot be loaded or linked.
    fn ensure_loaded(&mut self, class: &str) -> Result<()>;

    /// Load a class through the parent/default loader without resolving child-loader identities.
    ///
    /// # Errors
    /// Returns an error if parent class lookup fails unexpectedly.
    fn ensure_parent_loaded(&mut self, _class: &str) -> Result<Option<String>> {
        Ok(None)
    }

    /// Read reflection metadata for a loaded or loadable class.
    ///
    /// # Errors
    /// Returns an error if the class cannot be inspected.
    fn inspect_class(&mut self, class: &str) -> Result<ReflectedClassInfo>;

    /// Ensure the named class has completed initialization, including `<clinit>`.
    ///
    /// # Errors
    /// Returns an error if the class cannot be loaded or if initialization fails.
    fn ensure_class_initialized(
        &mut self,
        _heap: &mut duke_gc::Heap,
        _output: &mut dyn Write,
        class: &str,
    ) -> Result<()> {
        self.ensure_loaded(class)
    }

    /// Return the best-known code source path for the given class.
    ///
    /// Duke currently uses a coarse default path while bootstrapping richer
    /// class provenance support.
    ///
    /// # Errors
    /// Returns an error if class provenance lookup fails.
    fn code_source_for_class(&mut self, _class: &str) -> Result<Option<String>> {
        Ok(None)
    }

    /// Load `class` using the specific runtime `ClassLoader` object identified by `loader_ref`.
    ///
    /// # Errors
    /// Returns an error if the class cannot be loaded or linked under that runtime loader.
    fn ensure_loaded_with_runtime_loader(
        &mut self,
        _heap: &duke_gc::Heap,
        _loader_ref: u64,
        class: &str,
    ) -> Result<()> {
        self.ensure_loaded(class)
    }

    /// Resolve an instance field slot for the named class.
    ///
    /// # Errors
    /// Returns an error if the field cannot be resolved.
    fn instance_field_slot(&mut self, _class: &str, _field_name: &str) -> Result<usize> {
        Err(Error::InvalidFieldref { index: 0 })
    }

    /// Read an instance field from `object_ref`, validating it against the declaring class.
    ///
    /// # Errors
    /// Returns an error if the field cannot be resolved or read.
    fn read_instance_field(
        &mut self,
        _heap: &duke_gc::Heap,
        _object_ref: u64,
        _declaring_class: &str,
        _field_name: &str,
    ) -> Result<Slot> {
        Err(Error::InvalidFieldref { index: 0 })
    }

    /// Write an instance field on `object_ref`, validating it against the declaring class.
    ///
    /// # Errors
    /// Returns an error if the field cannot be resolved or written.
    fn write_instance_field(
        &mut self,
        _heap: &mut duke_gc::Heap,
        _object_ref: u64,
        _declaring_class: &str,
        _field_name: &str,
        _value: Slot,
    ) -> Result<()> {
        Err(Error::InvalidFieldref { index: 0 })
    }

    /// Read a static field from the named class.
    ///
    /// # Errors
    /// Returns an error if the field cannot be resolved or read.
    fn read_static_field(&mut self, _class: &str, _field_name: &str) -> Result<Slot> {
        Err(Error::InvalidFieldref { index: 0 })
    }

    /// Write a static field on the named class.
    ///
    /// # Errors
    /// Returns an error if the field cannot be resolved or written.
    fn write_static_field(&mut self, _class: &str, _field_name: &str, _value: Slot) -> Result<()> {
        Err(Error::InvalidFieldref { index: 0 })
    }

    /// Return the runtime `java/lang/ClassLoader` object for `class`, if known.
    ///
    /// # Errors
    /// Returns an error if runtime loader provenance lookup fails.
    fn runtime_loader_for_class(&mut self, _class: &str) -> Result<Option<u64>> {
        Ok(None)
    }

    /// Return all service-provider configuration files visible to a runtime loader.
    ///
    /// # Errors
    /// Returns an error if resource enumeration fails.
    fn service_configuration_files(
        &mut self,
        _heap: &duke_gc::Heap,
        _loader_ref: Option<u64>,
        _service_binary_name: &str,
    ) -> Result<Vec<Vec<u8>>> {
        Ok(Vec::new())
    }

    /// Return the deterministic class identity key for `class` in the current runtime.
    ///
    /// # Errors
    /// Returns an error if class identity resolution fails.
    fn class_key_for_loaded_class(&mut self, class: &str) -> Result<String> {
        Ok(class.to_string())
    }

    /// Return the deterministic class identity key for `class` under the given runtime loader.
    ///
    /// # Errors
    /// Returns an error if class identity resolution fails under that loader.
    fn class_key_for_runtime_loader(
        &mut self,
        _heap: &duke_gc::Heap,
        _loader_ref: u64,
        class: &str,
    ) -> Result<String> {
        self.class_key_for_loaded_class(class)
    }

    /// Return the deterministic class identity key for `class` as seen from `source_class`.
    ///
    /// # Errors
    /// Returns an error if class identity resolution fails for the source provenance.
    fn class_key_from_source(
        &mut self,
        class: &str,
        _source_class: Option<&str>,
    ) -> Result<String> {
        self.class_key_for_loaded_class(class)
    }

    /// Allocate a new heap instance for the named class, applying normal class initialization.
    ///
    /// # Errors
    /// Returns an error if allocation or class initialization fails.
    fn allocate_instance(
        &mut self,
        _heap: &mut duke_gc::Heap,
        _output: &mut dyn Write,
        _class: &str,
    ) -> Result<u64> {
        Err(Error::Unimplemented {
            mnemonic: "reflection constructor allocation",
        })
    }
}

/// A native handler that can call back into the interpreter to invoke Java methods
/// and query reflection metadata from the current loader/registry.
pub type CallbackNativeHandler = fn(
    args: &[Slot],
    heap: &mut duke_gc::Heap,
    output: &mut dyn Write,
    control: &mut NativeControl,
    ops: &mut dyn CallbackOps,
) -> Result<Option<Slot>>;

/// Stored in `NativeRegistry` — all existing handlers stay `Simple`.
#[derive(Copy, Clone, Debug)]
pub enum HandlerKind {
    /// A simple stateless native method handler.
    Simple(NativeHandler),
    /// A handler that delegates back to a callback trait or closure.
    Callback(CallbackNativeHandler),
}

/// Registry of native method implementations.
///
/// Maps `"class_name\x00method_name\x00descriptor"` to a handler kind.
///
/// # Examples
///
/// ```
/// use duke_interpreter::NativeRegistry;
///
/// let mut natives = NativeRegistry::new();
/// assert!(natives.get("java/lang/System", "exit", "(I)V").is_none());
/// ```
pub struct NativeRegistry {
    handlers: HashMap<String, HandlerKind>,
}

/// Build the lookup key for a native method: `"class\x00method\x00desc"`.
///
/// Using NUL as separator avoids ambiguity (JVM identifiers cannot contain NUL)
/// and reduces the three allocations previously required per lookup to one.
#[inline]
fn make_key(class: &str, method: &str, desc: &str) -> String {
    let mut key = String::with_capacity(class.len() + method.len() + desc.len() + 2);
    key.push_str(class);
    key.push('\x00');
    key.push_str(method);
    key.push('\x00');
    key.push_str(desc);
    key
}

impl NativeRegistry {
    /// Creates a new empty native registry.
    ///
    /// # Examples
    ///
    /// ```
    /// use duke_interpreter::NativeRegistry;
    ///
    /// let natives = NativeRegistry::new();
    /// ```
    #[must_use]
    pub fn new() -> Self {
        Self {
            handlers: HashMap::new(),
        }
    }

    fn insert_handler(&mut self, class: &str, method: &str, descriptor: &str, kind: HandlerKind) {
        self.handlers
            .insert(make_key(class, method, descriptor), kind);
    }

    /// Register a native method handler.
    pub fn register(
        &mut self,
        class: &str,
        method: &str,
        descriptor: &str,
        handler: NativeHandler,
    ) {
        self.insert_handler(class, method, descriptor, HandlerKind::Simple(handler));
    }

    /// Register a native method handler that can call back into the interpreter.
    pub fn register_callback(
        &mut self,
        class: &str,
        method: &str,
        descriptor: &str,
        handler: CallbackNativeHandler,
    ) {
        self.insert_handler(class, method, descriptor, HandlerKind::Callback(handler));
    }

    /// Look up a native handler for the given class/method/descriptor.
    ///
    /// Returns `Some` only for `Simple` handlers. Use [`get_kind`] to handle
    /// `Callback` variants.
    ///
    /// [`get_kind`]: NativeRegistry::get_kind
    #[must_use]
    pub fn get(&self, class: &str, method: &str, descriptor: &str) -> Option<NativeHandler> {
        match self.handlers.get(&make_key(class, method, descriptor))? {
            HandlerKind::Simple(h) => Some(*h),
            HandlerKind::Callback(_) => None,
        }
    }

    /// Look up any handler kind for the given class/method/descriptor.
    #[must_use]
    pub fn get_kind(&self, class: &str, method: &str, descriptor: &str) -> Option<HandlerKind> {
        self.handlers
            .get(&make_key(class, method, descriptor))
            .copied()
    }
}

impl Default for NativeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_class_registry_default() {
        let registry = ClassRegistry::default();
        assert!(!registry.contains("java/lang/Object"));
    }

    #[test]
    fn test_class_registry_get_mut_missing_class() {
        let mut registry = ClassRegistry::default();
        let result = registry.get_mut("MissingClass");
        match result {
            Err(duke_runtime::Error::ClassNotFound { name }) => assert_eq!(name, "MissingClass"),
            _ => panic!("Expected ClassNotFound error"),
        }
    }

    #[test]
    fn test_native_registry_default() {
        let natives = NativeRegistry::default();
        assert!(natives.get("java/lang/System", "exit", "(I)V").is_none());
    }

    #[test]
    fn ensure_loaded_with_code_source_uses_boot_archive_layout() {
        let jar_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/hello.jar");
        let mut registry = ClassRegistry::new();
        assert!(
            registry
                .ensure_loaded_with_code_source("HelloWorld", &jar_path.display().to_string())
                .expect("load HelloWorld from code source"),
            "zip-backed code source should resolve classes"
        );
        let class_key = registry.class_key_from_provenance(
            "HelloWorld",
            Some(&jar_path.display().to_string()),
            None,
        );
        assert!(registry.contains(&class_key));
        assert_eq!(
            registry.code_source_for_class(&class_key),
            Some(jar_path.display().to_string().as_str())
        );
    }
}

#[cfg(test)]
mod callback_ops_tests {
    use super::*;
    use duke_gc::Heap;

    struct MockOps;
    impl CallbackOps for MockOps {
        fn invoke(
            &mut self,
            _heap: &mut Heap,
            _output: &mut dyn std::io::Write,
            _class: &str,
            _method: &str,
            _descriptor: &str,
            _args: Vec<crate::Slot>,
        ) -> Result<Option<crate::Slot>> {
            Ok(None)
        }
        fn ensure_loaded(&mut self, _class: &str) -> Result<()> {
            Ok(())
        }
        fn inspect_class(&mut self, _class: &str) -> Result<ReflectedClassInfo> {
            Err(Error::Unimplemented {
                mnemonic: "inspect_class",
            })
        }
    }

    #[test]
    fn test_callback_ops_defaults() {
        let mut ops = MockOps;
        let mut heap = Heap::new();
        let mut output = Vec::new();

        assert!(
            ops.ensure_class_initialized(&mut heap, &mut output, "TestClass")
                .is_ok()
        );
        assert!(ops.code_source_for_class("TestClass").unwrap().is_none());
        assert!(
            ops.ensure_loaded_with_runtime_loader(&heap, 0, "TestClass")
                .is_ok()
        );

        let err = ops.instance_field_slot("TestClass", "field").unwrap_err();
        assert!(matches!(err, Error::InvalidFieldref { index: 0 }));

        let err = ops
            .read_instance_field(&heap, 0, "TestClass", "field")
            .unwrap_err();
        assert!(matches!(err, Error::InvalidFieldref { index: 0 }));

        let err = ops
            .write_instance_field(&mut heap, 0, "TestClass", "field", crate::Slot::Int(0))
            .unwrap_err();
        assert!(matches!(err, Error::InvalidFieldref { index: 0 }));

        let err = ops.read_static_field("TestClass", "field").unwrap_err();
        assert!(matches!(err, Error::InvalidFieldref { index: 0 }));

        let err = ops
            .write_static_field("TestClass", "field", crate::Slot::Int(0))
            .unwrap_err();
        assert!(matches!(err, Error::InvalidFieldref { index: 0 }));

        assert!(ops.runtime_loader_for_class("TestClass").unwrap().is_none());
        assert_eq!(
            ops.class_key_for_loaded_class("TestClass").unwrap(),
            "TestClass"
        );
        assert_eq!(
            ops.class_key_for_runtime_loader(&heap, 0, "TestClass")
                .unwrap(),
            "TestClass"
        );
        assert_eq!(
            ops.class_key_from_source("TestClass", None).unwrap(),
            "TestClass"
        );

        let err = ops
            .allocate_instance(&mut heap, &mut output, "TestClass")
            .unwrap_err();
        assert!(matches!(err, Error::Unimplemented { .. }));
    }
}
